apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: website  
spec:
  ports:
  - name: http
    port: 80
    #protocol: TCP
    targetPort: 80
  selector:
    app: website
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.168.0.123  
